### PR TITLE
Extensive validity check for SMSPeer and SMSMessage

### PR DESCRIPTION
**Pull request by ricdezen**
- Added Enums to identify problems with an invalid SMSPeer or SMSMessage.
- Added static method to both classes to perform checks on said validity.
- Modified tests accordingly.

### CODE REVIEW

**Comment by bortoletti-giorgia** [comment]
I checked and I approve the merge.

**Comment by turcato-niccolo** [comment]
> I checked and I approve the merge.

You should use the Approve comment then: you can find it on the top right in the tab "files changed"

**Review by turcato-niccolo — CHANGES_REQUESTED** [review]
Line 28 SMSMessage
`public SMSMessage(SMSPeer peer, String data) ` there should be @throws `InvalidMessageException`

Same for `SMSPeer `at line 26

The rest is perfect, I hope not to look silly😂😂

**Review by turcato-niccolo — APPROVED** [review]
Thank you😍

**Pull request merged**
